# Generated by Django 3.2 on 2021-05-13 08:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Columns',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('limit', models.IntegerField(null=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Rows',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=70)),
                ('description', models.TextField(blank=True, max_length=400)),
                ('priority', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='Low', max_length=6)),
                ('difficulty', models.CharField(choices=[('Easy', 'Easy'), ('Intermediate', 'Intermediate'), ('Hard', 'Hard')], default='Easy', max_length=12)),
                ('publishDate', models.DateTimeField(auto_now_add=True, verbose_name='date time published')),
                ('position', models.IntegerField(default=1, verbose_name='Position')),
                ('User', models.ManyToManyField(related_name='danie', to=settings.AUTH_USER_MODEL)),
                ('columnId', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='columnId', to='kanban.columns')),
                ('rowId', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rowId', to='kanban.rows')),
            ],
            options={
                'ordering': ['columnId', 'rowId', 'position'],
            },
        ),
    ]
