# Generated by Django 3.2 on 2021-06-09 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='User',
        ),
    ]
